models/IssueHistory.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "issue_history".
 *
 * @property int $issue_id
 * @property int $userid
 * @property int $book_id
 * @property string $issue_date
 * @property string $status
 *
 * @property Users $user
 * @property Books $book
 */
class IssueHistory extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'issue_history';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['userid', 'book_id', 'issue_date', 'status'], 'required'],
            [['userid', 'book_id'], 'integer'],
            [['issue_date'], 'safe'],
            [['status'], 'string'],
            [['userid'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['userid' => 'userid']],
            [['book_id'], 'exist', 'skipOnError' => true, 'targetClass' => Books::className(), 'targetAttribute' => ['book_id' => 'book_id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'issue_id' => 'Issue ID',
            'userid' => 'Userid',
            'book_id' => 'Book ID',
            'issue_date' => 'Issue Date',
            'status' => 'Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(Users::className(), ['userid' => 'userid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBook()
    {
        return $this->hasOne(Books::className(), ['book_id' => 'book_id']);
    }
}

controllers/IssueHistoryController.php
<?php

namespace app\controllers;

use Yii;
use app\models\IssueHistory;
use app\models\IssueHistorySearch;
use yii\web\Controller;
use app\models\Books;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * IssueHistoryController implements the CRUD actions for IssueHistory model.
 */
class IssueHistoryController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all IssueHistory models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new IssueHistorySearch();

        $userid = Yii::$app->user->identity->id;
        $params = Yii::$app->request->queryParams;

        // Add userid as a filter in case the user is not admin
        if(Yii::$app->user->identity->role != 'admin')
        {
            $filter = ['userid' => $userid];
            if(isset($params['IssueHistorySearch']))
            {
                $filter = array_merge($filter, $params['IssueHistorySearch']);
            }
            $params = ['IssueHistorySearch' => $filter];
        }
        $dataProvider = $searchModel->search($params);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCreatePending()
    {
        $book_id = Yii::$app->request->get()['id'];

        $model = new IssueHistory();
        $model->book_id = $book_id;
        $model->userid = Yii::$app->user->identity->id;
        $model->issue_date = date('Y-m-d H:i:s');
        $model->status = 'pending';
        $model->save();

        $book = Books::findOne($book_id);
        $book->issued_status = 'pending';
        $book->save();

        return yii::$app->runaction('books/index');
    }
    public function actionApprove()
    {
        $issue_id = Yii::$app->request->get()['id'];

        $issueHistory = IssueHistory::findOne($issue_id);
        $issueHistory->status = 'approved';
        $issueHistory->book->issued_status = 'issued';
        $issueHistory->save();
        $issueHistory->book->save();

        return yii::$app->runaction('issue-history/index');
    }
    
    /**
     * Displays a single IssueHistory model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new IssueHistory model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new IssueHistory();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->issue_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing IssueHistory model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->issue_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing IssueHistory model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the IssueHistory model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return IssueHistory the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = IssueHistory::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/issue-history/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\IssueHistory */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="issue-history-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'userid')->textInput() ?>

    <?= $form->field($model, 'book_id')->textInput() ?>

    <?= $form->field($model, 'issue_date')->textInput() ?>

    <?= $form->field($model, 'status')->dropDownList([ 'pending' => 'Pending', 'approved' => 'Approved', ], ['prompt' => '']) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/issue-history/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\IssueHistorySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="issue-history-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'issue_id') ?>

    <?= $form->field($model, 'userid') ?>

    <?= $form->field($model, 'book_id') ?>

    <?= $form->field($model, 'issue_date') ?>

    <?= $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/issue-history/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\IssueHistory */

$this->title = 'Create Issue History';
$this->params['breadcrumbs'][] = ['label' => 'Issue Histories', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="issue-history-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/issue-history/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\IssueHistorySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Issue Histories';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="issue-history-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'user.username',
            'book.book_id',
            'book.book_title',
            'issue_date',
            'status',

            [
                'class' => 'yii\grid\ActionColumn',
                'visible' => Yii::$app->user->identity->role == 'admin',
            ],
            [
                'format' => 'raw',
                'visible' => Yii::$app->user->identity->role == 'admin',
                'value' => function($model, $key, $index, $column) {
                    if($model->status == 'pending')
                    {
                        return Html::a(
                            '<i class="fa fa-euro">Approve</i>',
                            Url::to(['issue-history/approve', 'id' => $model->issue_id]),
                            [
                                'id'=>'grid-custom-button',
                                'data-pjax'=>true,
                                'action'=>Url::to(['issue-history/approve', 'id' => $model->issue_id]),
                                'class'=>'button btn btn-default',
                            ]
                        );
                    } else {
                        return '';
                    }
                }
            ]
        ],
    ]); ?>
</div>

views/issue-history/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\IssueHistory */

$this->title = 'Update Issue History: ' . $model->issue_id;
$this->params['breadcrumbs'][] = ['label' => 'Issue Histories', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->issue_id, 'url' => ['view', 'id' => $model->issue_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="issue-history-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/issue-history/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\IssueHistory */

$this->title = $model->issue_id;
$this->params['breadcrumbs'][] = ['label' => 'Issue Histories', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="issue-history-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->issue_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->issue_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'issue_id',
            'userid',
            'book_id',
            'issue_date',
            'status',
        ],
    ]) ?>

</div>